#!/usr/bin/env node
/**
 * 347movies — NYC photo gallery registration (the "drop-in" flow).
 *
 * Drop a photo into public/images/ (nyc-*.jpg/jpeg/webp/png), then run `npm run images`.
 * This script wires the new photo into the site with NO manual CSS edits:
 *
 *   1. Scans public/images/ for nyc-* images (sorted by name).
 *   2. Assigns the named roles by filename suffix (nyc-*-hero, -noir, -skyline,
 *      -notfound / -404); otherwise a role KEEPS its current committed photo (a new photo
 *      never silently displaces an existing one). Roles with no current photo fall back by
 *      position. New photos join the home-hero rotation automatically (the hero plus the
 *      next three, by name) — and can be pinned to a role by naming them e.g. nyc-*-hero.jpg.
 *   3. Rewrites the delimited --img-* block in public/css/style.css :root (between the
 *      BEGIN/END generated markers). The home hero rotation takes the hero plus the next
 *      three photos (--img-rotate-1/2/3/4) so the crossfade picks up new shots automatically.
 *   4. Rewrites the hero/noir LCP preload hrefs in public/index.html and public/genre.html
 *      to match, so the LCP image stays correct.
 *   5. Writes public/images/registry.json (inventory + assignments) for transparency.
 *
 * Idempotent and fail-closed: refuses to run if the markers are missing (so it can never
 * mangle a hand-edited stylesheet) or if no nyc-* photos exist.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const IMAGES_DIR = join(ROOT, "public", "images");
const CSS_PATH = join(ROOT, "public", "css", "style.css");
const HOME_PATH = join(ROOT, "public", "index.html");
const GENRE_PATH = join(ROOT, "public", "genre.html");
const REGISTRY_PATH = join(IMAGES_DIR, "registry.json");

const BEGIN = "/* BEGIN generated by scripts/register-images.mjs — do not edit by hand */";
const END = "/* END generated */";
const ROLE_ORDER = ["hero", "noir", "skyline", "notfound"];
const SUFFIX_ROLE = [
  ["-hero.", "hero"],
  ["-noir.", "noir"],
  ["-skyline.", "skyline"],
  ["-notfound.", "notfound"],
  ["-404.", "notfound"],
];

/**
 * Ordered list of nyc-* photos in public/images/. Order = leading numeric prefix
 * (01-, 02-, …) first, then by name — so the rotation order is tunable by renaming a
 * photo with a numeric prefix (01- leads the home-hero crossfade).
 */
function scanPhotos() {
  return readdirSync(IMAGES_DIR)
    .filter((f) => /^(?:\d+-)?nyc-.*\.(jpe?g|webp|png)$/i.test(f))
    .sort((a, b) => {
      const na = parseInt(a, 10);
      const nb = parseInt(b, 10);
      if (Number.isFinite(na) && Number.isFinite(nb) && na !== nb) return na - nb;
      return a.localeCompare(b);
    });
}

/** Read the current committed role assignments from the generated CSS block. */
function readCurrentRoles(css) {
  const roles = {};
  const block = css.slice(css.indexOf(BEGIN), css.indexOf(END));
  for (const m of block.matchAll(/--img-(hero|noir|skyline|notfound): url\("\/images\/([^"]+)"\)/g)) {
    roles[m[1]] = m[2];
  }
  return roles;
}

/**
 * Assign named roles: filename suffix wins; otherwise a role keeps its current committed
 * photo (so a new photo never silently displaces an existing one); roles with no current
 * photo fall back to the first unassigned photo by name.
 */
function assignRoles(photos, currentRoles) {
  const bySuffix = new Map();
  for (const photo of photos) {
    for (const [needle, role] of SUFFIX_ROLE) {
      if (photo.toLowerCase().includes(needle) && !bySuffix.has(role)) {
        bySuffix.set(role, photo);
        break;
      }
    }
  }
  const roles = {};
  for (const role of ROLE_ORDER) {
    if (bySuffix.has(role)) roles[role] = bySuffix.get(role);
    else if (currentRoles[role] && photos.includes(currentRoles[role])) roles[role] = currentRoles[role];
  }
  const used = new Set(Object.values(roles));
  const pool = photos.filter((p) => !used.has(p));
  for (const role of ROLE_ORDER) {
    if (!roles[role] && pool.length) roles[role] = pool.shift();
  }
  return roles;
}

function fail(message) {
  console.error(`REFUSE  ${message}`);
  process.exit(1);
}

function main() {
  const photos = scanPhotos();
  if (photos.length === 0) {
    fail(`no nyc-* photos found in ${IMAGES_DIR} — nothing to register (the existing backgrounds are kept)`);
  }

  const css = readFileSync(CSS_PATH, "utf8");
  const start = css.indexOf(BEGIN);
  const end = css.indexOf(END);
  if (start === -1 || end === -1 || end <= start) {
    fail(`the BEGIN/END generated markers are missing from ${CSS_PATH} — a hand-edit removed them; fix before re-running`);
  }

  const roles = assignRoles(photos, readCurrentRoles(css));
  // The hero rotation: the hero photo first (LCP), then the next two by name — so a new
  // photo joins the crossfade automatically, and the hero always leads.
  const hero = roles.hero || photos[0];
  const nonHero = photos.filter((p) => p !== hero);
  const rotation = [hero, nonHero[0] || hero, nonHero[1] || hero, nonHero[2] || hero];

  const lines = [
    `  --img-hero: url("/images/${roles.hero || hero}");`,
    `  --img-noir: url("/images/${roles.noir || hero}");`,
    `  --img-skyline: url("/images/${roles.skyline || hero}");`,
    `  --img-notfound: url("/images/${roles.notfound || hero}");`,
    `  --img-rotate-1: url("/images/${rotation[0]}");`,
    `  --img-rotate-2: url("/images/${rotation[1]}");`,
    `  --img-rotate-3: url("/images/${rotation[2]}");`,
    `  --img-rotate-4: url("/images/${rotation[3]}");`,
  ].join("\n");
  const block = `${BEGIN}\n${lines}\n  ${END}`;
  const nextCss = css.slice(0, start) + block + css.slice(end + END.length);
  writeFileSync(CSS_PATH, nextCss);

  // Keep the LCP preloads in sync with the hero/noir roles.
  const preloadRe = /(rel="preload" as="image" href="\/images\/)([^"]+)(" fetchpriority="high")/;
  const home = readFileSync(HOME_PATH, "utf8");
  const nextHome = home.includes(`href="/images/${roles.hero || hero}" fetchpriority`)
    ? home
    : home.replace(preloadRe, `$1${roles.hero || hero}$3`);
  writeFileSync(HOME_PATH, nextHome);

  const genre = readFileSync(GENRE_PATH, "utf8");
  const nextGenre = genre.includes(`href="/images/${roles.noir || hero}" fetchpriority`)
    ? genre
    : genre.replace(preloadRe, `$1${roles.noir || hero}$3`);
  writeFileSync(GENRE_PATH, nextGenre);

  const registry = {
    generated: new Date().toISOString(),
    source: "scripts/register-images.mjs",
    images: photos,
    roles,
    rotation,
  };
  writeFileSync(REGISTRY_PATH, JSON.stringify(registry, null, 2) + "\n");

  console.log(`Registered ${photos.length} photo(s):`);
  for (const [role, photo] of Object.entries(roles)) console.log(`  ${role.padEnd(9)} → ${photo}`);
  console.log(`  rotation   → ${rotation.join(", ")}`);
  console.log(`Updated ${CSS_PATH}, preloads, and ${REGISTRY_PATH}.`);
}

main();
